//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by manager.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MANAGETYPE                  129
#define IDD_DIALOG_ATT_EDIT             129
#define IDD_DIALOG_LOGIN                131
#define IDR_MAINFRAME1                  131
#define IDD_DIALOG_USER                 132
#define IDD_DIALOG_FOLK                 133
#define IDD_DIALOG_ADD                  134
#define IDD_DIALOG_STATUS               135
#define IDD_DIALOG_EDUCATION            136
#define IDD_DIALOG_POLITICAL            137
#define IDD_DIALOG_DEPT                 138
#define IDD_DIALOG_PAY                  139
#define IDD_DIALOG_DUTY                 140
#define IDD_DIALOG_TECHNICAL            141
#define IDD_DIALOG_BROWSE               142
#define IDD_PAGE_BASEINFO               144
#define IDD_PAGE_FAMILY                 145
#define IDD_PAGE_HISTORY                146
#define IDD_PAGE_HONOR                  147
#define IDD_PAGE_QUALIFICATION          148
#define IDD_PAGE_TRAIN                  149
#define IDD_PAGE_RECORD                 150
#define IDD_DIALOG_SEARCH               151
#define IDD_DIALOG_STAT                 153
#define IDD_DIALOG_NOTEPAD              154
#define IDD_DIALOG_BOOK                 155
#define IDD_DIALOG_BOOKINFO             158
#define IDD_DIALOG_ATT_STAT             159
#define IDD_DIALOG_ATT_WORKPLAN         160
#define IDD_PROPPAGE_1                  161
#define IDD_PAGE_ATTWORK                161
#define IDD_PROPPAGE_2                  162
#define IDD_PAGE_ATTOVERTIME            162
#define IDD_PROPPAGE_3                  163
#define IDD_PAGE_ATTLEAVE               163
#define IDD_PROPPAGE_4                  164
#define IDD_PAGE_ATTERRAND              164
#define IDB_BITMAP_BG                   169
#define IDB_BITMAP_LOGIN                171
#define IDC_COMBO1                      1000
#define IDC_EDIT1                       1001
#define IDC_LIST_USERNAME               1002
#define IDC_EDIT_PHONE1                 1002
#define IDC_EDIT_PHONE2                 1003
#define IDC_BUTTON_NEW                  1004
#define IDC_EDIT_MPHONE                 1004
#define IDC_BUTTON_DELETE               1005
#define IDC_EDIT2                       1006
#define IDC_BUTTON_SAVE                 1006
#define IDC_CHK_SEEKBYTIME              1006
#define IDC_EDIT3                       1007
#define IDC_CHK_SEEKBYPERSON            1007
#define IDC_CHECK1                      1008
#define IDC_EDIT_OUTLAY                 1008
#define IDC_BUTTON_CANCEL               1009
#define IDC_LIST1                       1010
#define IDC_EDT_SEEKPERSONID            1010
#define IDC_EDT_SEEKPERSONNAME          1011
#define IDC_EDIT_DATA                   1015
#define IDC_STATIC_DATA                 1016
#define IDC_COMBO_CONTENT               1017
#define IDC_STAT_EDT_TIME               1017
#define IDC_COMBO_CONDITION             1018
#define IDC_STAT_DATETIMEPICKER_STARTTIME 1018
#define IDC_EDIT_NAME                   1019
#define IDC_STAT_DATETIMEPICKER_ENDTIME 1019
#define IDC_EDIT_CODE                   1020
#define IDC_STAT_PROGRESS               1020
#define IDC_TAB1                        1021
#define IDC_STAT_BTN_STAT               1021
#define IDC_STAT_CHK_SEEKBYTIME         1022
#define IDC_STAT_CHK_SEEKBYPERSON       1023
#define IDC_BUTTON_SEARCH               1024
#define IDC_STAT_EDT_SEEKTIME           1024
#define IDC_EDIT_AGE                    1025
#define IDC_STAT_EDT_SEEKPERSONID       1025
#define IDC_STAT_EDT_SEEKPERSONNAME     1026
#define IDC_DATETIMEPICKER_BIRTHDAY     1027
#define IDC_STAT_BTN_SEEK               1027
#define IDC_COMBO_FOLK                  1028
#define IDC_STAT_LIST                   1028
#define IDC_COMBO_POLITICAL             1029
#define IDC_WORKSTAT_DATETIMEPICKER3    1029
#define IDC_COMBO_MARRY                 1030
#define IDC_WORKSTAT_DATETIMEPICKER4    1030
#define IDC_COMBO_EDUCATION             1031
#define IDC_WORKSTAT_DATETIMEPICKER1    1031
#define IDC_EDIT_CARDCODE               1032
#define IDC_WORKSTAT_DATETIMEPICKER2    1032
#define IDC_EDIT_NATIVE                 1033
#define IDC_WORKPLAN_MODIFY             1033
#define IDC_DATETIMEPICKER_DATE1        1034
#define IDC_WORKPLAN_RESET              1034
#define IDC_DATETIMEPICKER_DATE2        1035
#define IDC_EDT_IOTIME                  1035
#define IDC_COMBO_ISWORKER              1036
#define IDC_EDT_DEPARTID                1036
#define IDC_COMBO_ABOUTPAY              1037
#define IDC_EDT_DEPARTNAME              1037
#define IDC_COMBO_DUTY                  1038
#define IDC_EDT_PERSONID                1038
#define IDC_COMBO_TECHNICAL             1039
#define IDC_RADIO_OUT                   1039
#define IDC_COMBO_DEPT                  1040
#define IDC_RADIO_IN                    1040
#define IDC_EDIT_PHONE                  1041
#define IDC_BTN_ADDPERSON               1041
#define IDC_EDIT_MOBILE                 1042
#define IDC_BTN_ADDALL                  1042
#define IDC_EDIT_SCHOOL                 1043
#define IDC_BTN_ADDDEPART               1043
#define IDC_EDIT_SUBJECT                1044
#define IDC_PROGRESS1                   1044
#define IDC_DATETIMEPICKER_GDATE        1045
#define IDC_EDT_PERSONNAME              1045
#define IDC_EDIT_ADDRESS                1046
#define IDC_BTN_DELETEATTEND            1046
#define IDC_EDIT_EMAIL                  1047
#define IDC_BTN_SEEKIO                  1047
#define IDC_EDIT_DEPT2                  1048
#define IDC_EDIT_DEPT3                  1049
#define IDC_OVERTIME_DATETIMEPICKER     1049
#define IDC_COMBO_SEX                   1050
#define IDC_EDT_OVERTIME_PERSONID       1050
#define IDC_EDT_OVERTIME_HOUR           1051
#define IDC_EDT_OVERTIME_PERSONNAME     1052
#define IDC_BTN_OVERTIME_ADD            1053
#define IDC_BUTTON_MODIFY               1054
#define IDC_BTN_OVERTIME_DELETEATTEND   1054
#define IDC_DATETIMEPICKER1             1055
#define IDC_BTN_OVERTIME_SEEKIO         1055
#define IDC_EDIT_TERM                   1057
#define IDC_EDT_LEAVE_STARTTIME         1057
#define IDC_EDIT_RESULT                 1058
#define IDC_EDT_LEAVE_PERSONID          1058
#define IDC_DATETIMEPICKER2             1059
#define IDC_EDT_LEAVE_ENDTIME           1059
#define IDC_DATETIMEPICKER3             1060
#define IDC_EDT_LEAVE_PERSONNAME        1060
#define IDC_BUTTON_SAVE1                1061
#define IDC_BTN_LEAVE_ADD               1061
#define IDC_EDT_LEAVE_REASON            1062
#define IDC_BTN_LEAVE_SEEKIO            1063
#define IDC_BTN_LEAVE_DELETEATTEND      1064
#define IDC_LIST3                       1065
#define IDC_EDT_ERRAND_STARTTIME        1066
#define IDC_EDT_ERRAND_PERSONID         1067
#define IDC_LIST2                       1068
#define IDC_EDT_ERRAND_ENDTIME          1068
#define IDC_EDT_ERRAND_PERSONNAME       1069
#define IDC_EDT_ERRAND_DESCRIPTION      1070
#define IDC_EDIT_CONTENT                1071
#define IDC_BTN_ERRAND_ADD              1071
#define IDC_DATETIMEPICKER_DATE         1072
#define IDC_BTN_ERRAND_DELETEATTEND     1072
#define IDC_EDIT_SORT                   1073
#define IDC_BTN_ERRAND_SEEKIO           1073
#define IDC_EDIT_TITLE                  1074
#define IDC_LIST4                       1074
#define IDC_RICHEDIT1                   1075
#define IDC_BUTTON1                     1076
#define IDC_BUTTON_ALL                  1077
#define IDC_EDIT_CALL                   1078
#define IDC_EDIT_QQ                     1079
#define IDC_EDIT_COMMENTS               1080
#define IDC_EDIT_RELATION               1081
#define IDC_DATETIMEPICKER_BIRTH        1082
#define IDC_EDIT_UNIT                   1083
#define IDC_EDIT_DUTY                   1084
#define IDC_EDIT_POLITICAL              1085
#define IDC_EDIT_DEPT                   1088
#define IDC_EDIT_SORTS                  1089
#define IDC_EDIT_REASON1                1090
#define IDC_EDIT_REASON2                1091
#define IDC_EDIT_TECH                   1092
#define IDC_EDIT_MODE                   1093
#define IDC_DATETIMEPICKER_DATE0        1094
#define IDC_TAB2                        1095
#define IDC_COMBO_PERSONID              1096
#define IDC_COMBO_DEPARTMENT            1097
#define ID_SYS_SET                      32771
#define ID_SYS_FOLK                     32773
#define ID_SYS_WORKERTYPE               32774
#define ID_SYS_KNOWLEAGE                32775
#define ID_SYS_POLITY                   32776
#define ID_SYS_DEPTYPE                  32777
#define ID_SYS_SALARY                   32778
#define ID_SYS_TECH                     32779
#define ID_SYS_POST                     32780
#define ID_SYS_USER                     32781
#define ID_SYS_RELOAD                   32782
#define ID_SYS_QUIT                     32783
#define ID_PER_BROWSE                   32784
#define ID_PER_SEARCH                   32785
#define ID_PER_SUM                      32786
#define ID_MEMO_NOTEPAD                 32787
#define ID_MEMO_BOOK                    32788
#define ID_ATT_RECORD                   32804
#define ID_MENUITEM32805                32805
#define ID_ATT_STAT                     32806
#define ID_MENUITEM32807                32807
#define ID_DATABASE_BACKUP              32808
#define ID_DATABASE_RECOVER             32809
#define ID_ATT_SET                      32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
